CREATE TABLE TW_T1_ITEM (
    T1_ID SERIAL PRIMARY KEY,
    T1_TITLE VARCHAR(1000),
    T1_PICTURE_LINK VARCHAR(1000),
    T1_CURRENT_LOCATION VARCHAR(1000),
    T1_FOUND_LOCATION VARCHAR(1000),
    T1_FOUND_DATE DATE,
    T1_WHO_FOUND VARCHAR(1000),
    T1_IS_RETRIEVED BOOLEAN,
    T1_WHO_RETRIEVED VARCHAR(1000),
    T1_RETRIEVED_DATE DATE
);

CREATE SEQUENCE T1_ITEM_ID_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;